### PR TITLE
[util] Changed malloc to allocate in chunks of 4 bytes

### PR DESCRIPTION
**Pull request by jprestwo**
Signed-off-by: James Prestwood <james.prestwood@intel.com>

### CODE REVIEW

**Comment by grgustaf** [comment]
Note: the reason we're considering this is in case it helps with #924; otherwise no point I think.

**Comment by pfalcon** [comment]
Weird. I believe C standard *requires* pointer returned by malloc to have a natural alignment for the platform. You guys use Zephyr's (i.e. newlib's) malloc(), do you want to say it's not compliant?

**Comment by pfalcon** [comment]
Not a C standard, but Linux man page for reference:

> The  malloc()  and calloc() functions return a pointer to the allocated memory that is suitably aligned for any kind of variable.

**Comment by grgustaf** [comment]
OK, I checked and on A101 at least it always returns 8-byte aligned pointers. So we can probably close this.

**Pull request closed without merging**
