### PR TITLE
[util] Added Math.random() api

### PR DESCRIPTION
**Pull request by jimmy-huang**
Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

**Comment by grgustaf** [comment]
Does this conflict with pulling in the full math library by editing fragments/jerry_feature.base?

If so, we might want to either solve that or name this something else.

**Comment by jimmy-huang** [comment]
Yeah, it will conflict, i think a better way would be to detect if the jerry math feature is enabled or not before including this module.  I can probably look into it or you want this landed soon, then I can just rename it.

**Comment by jimmy-huang** [comment]
@grgustaf changed to MathStubs to avoid conflict

**Comment by jimmy-huang** [comment]
@grgustaf updated patch

**Pull request merged**
