### PR TITLE
Ram panacea

### PR DESCRIPTION
**Pull request by grgustaf**

### CODE REVIEW

**Comment by jimmy-huang** [comment]
this is awesome, so why did we use k_malloc at the first place?  Because Zephyr wasn't intended to be used with newlib originally?

**Comment by grgustaf** [comment]
Probably in our very first tests, there was no malloc because we weren't using newlib, so we just didn't realize that became available when we added it. I guess there should be some kind of code size (ROM) penalty for bringing in that good memory management, maybe I should check that.

**Comment by grgustaf** [comment]
Digging into that, actually we save 1300 bytes, primarily from dropping the pool memory allocator. So this actually turns out to be a win on both RAM and ROM fronts.

**Comment by jimmy-huang** [comment]
+1

**Pull request merged**
