### PR TITLE
[net-config] Update function name on net-config.md to fix #1401

### LINKED ISSUE #1401: [net-config] Function netConfig.setStaticIP() is undefined
### Description

I test net-config APIs and get an error. The function netConfig.setStaticIP() is undefined.
 

### Test Code

Simple test:
```
console.log("simple test");

var WebSocket = require("ws");
var netConfig = require("net-config");

var IPv6 = "2001:db8::100";
console.log("----mark----");
var IPState = netConfig.setStaticIP(IPv6);
console.log("setStaticIP(IPv6): " + IPState + " expected result 'true'");
```

 

### Steps to Reproduction

1. Run simple test on a101
2. Check console log.
 

### Actual Result

Log:
```
simple test
----mark----
Error: Expected a function.
```

 

### Expected Result

Work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 5726f4e | Arduino 101 | July 25, 2017 | Fail

### PR DESCRIPTION
**Pull request by cuiyanx**
Fixed #1401

Signed-off-by: Cui Yan <yanx.cui@intel.com>

### CODE REVIEW

**Comment by jprestwo** [comment]
+1

**Comment by grgustaf** [comment]
Actually, since IP is an acronym, let's instead fix the API to be called setStaticIP.

**Comment by cuiyanx** [comment]
@grgustaf OK, I will close this PR and update test case.

**Comment by grgustaf** [comment]
You could resubmit the other patch under this PR if you like.

**Pull request closed without merging**
