### PR TITLE
Fix sensor

### PR DESCRIPTION
**Pull request by jimmy-huang**

### CODE REVIEW

**Comment by grgustaf** [comment]
+1

**Comment by jimmy-huang** [comment]
@kenchris zephyr driver for the bmi160 claims to support up to 3200hz, but the max I was able to set without returning an error was 1600hz.

**Comment by kenchris** [comment]
Yeah 32MHz is the max frequency of the ARC core, and it has to do lots of work so that is still pretty good

**Comment by grgustaf** [comment]
@kenchris, stay away from that guy! http://goo.gl/7nG4mb

Sorry if I'm made this joke before. :)

**Comment by kenchris** [comment]
Hahaha, yeah please disregard my other comment... weekend+beers you know :)

**Pull request merged**
