### PR TITLE
[ashell] Disable PME from Ashell/IDE to gain more ROM

### PR DESCRIPTION
**Pull request by jimmy-huang**
Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

**Comment by poussa** [comment]
+1

**Comment by grgustaf** [comment]
This is fine but after disabling UART we may not need more space savings right now, in which case we could leave it in. Let's keep it on the back burner for the moment.

**Comment by poussa** [comment]
yeah, let's keep PME on ide around for now.

**Comment by jimmy-huang** [comment]
I am closing this until further ROM is needed.

**Pull request closed without merging**
