### PR TITLE
[Makefile] Denote generated files with a comment and clean up on clean

### PR DESCRIPTION
**Pull request by grgustaf**
The prj.conf, prj.mdef, arc/prj.conf, and src/Makefile files are all
generated at build time, so add a comment to each to that effect and
delete them in make clean.

Signed-off-by: Geoff Gustafson <geoff@linux.intel.com>

### CODE REVIEW

**Comment by jimmy-huang** [comment]
+1

**Comment by poussa** [comment]
While you are at it, can you add cleanup to the jerryscript libs as well. To address the issue below:

```
$ make clean
$ find . -name '*.a'
./deps/iotivity-constrained/deps/tinydtls/libtinydtls.a
./deps/jerryscript/build/lib/libjerry-libc.a
./deps/jerryscript/build/lib/libjerry-core.a
./deps/jerryscript/build/lib/libjerry-libm.a
```

**Comment by grgustaf** [comment]
This should have addressed @poussa 's request. (iotivity-constrained not merged yet, so not that part)

**Comment by jimmy-huang** [comment]
lgtm

**Pull request merged**
