### PR TITLE
Buffer validation

### PR DESCRIPTION
**Pull request by grgustaf**

### CODE REVIEW

**Comment by grgustaf** [comment]
I tested all modules affected by the second patch except dgram.

**Comment by grgustaf** [comment]
Also tested with UDP6 on A101, so this should be solid.

**Comment by grgustaf** [comment]
Added two tweaks: moved magic number to first four bytes of private struct, so it should be guaranteed to be safe to read... even if the user passes us a different JS object w/ a different handle type, because every handle has at least four bytes.

Second, I also check that the prototype of the given object matches the one I set.

**Comment by jimmy-huang** [comment]
+1

**Pull request merged**
