### PR TITLE
[build] Changing DEV to ASHELL to make things clearer

### PR DESCRIPTION
**Pull request by brianjjones**
This will also cause DEV=ashell to no longer be supported. This
helps remove confusion about building ashell the proper way.

Signed-off-by: Brian Jones <brian.j.jones@intel.com>

### CODE REVIEW

**Comment by grgustaf** [comment]
So just to clarify, I don't think we intend the user to pass DEV or ASHELL variable on the command line anymore; instead they should just make the 'ashell' or 'ide' target. Right?

So this is fine, it's just an internal variable. But please also add a check for the user setting DEV and tell them to run "make ashell" or "make ide" instead.

**Comment by brianjjones** [comment]
Yes, DEV=ashell should never be used now.  However I'm hesitant to add a warning for obsolete build options, it seems like that adds unnecessary bloat to our already complex Makefile.  However, I'm all for making a generic "This is not a supported build option" message that then prints make help.  This informs the user what they are doing is wrong, and provides them with the list of correct options.  Would that be acceptable?

**Comment by grgustaf** [comment]
That's not really going to work here because you can't check for every possible environment variable they have set. You have to specifically check for DEV for this to work. This is basically just a matter of having a clean deprecation path. It is mainly to help us, so that for the next few months if we type DEV=ashell out of habit, we will get an error message. After a while we can remove it.

**Comment by grgustaf** [comment]
You could also throw a fix for #920 into this patch. (And maybe grep for any other references to DEV=)

**Comment by jimmy-huang** [comment]
I think it would be nice to standardize some of the make commands, right now there's VARIANT=debug/release, SNAPSHOT=on/off, TRACE=on/off ASHELL=y/n, most if not all of these are true/false variants, why not just use the same for all of them, I am not sure which one is better.

**Comment by grgustaf** [comment]
Well ASHELL is really an internal make variable the user shouldn't know about.

I think on/off are decent for the others. VARIANT is odd, yeah, but that can wait for another day.

**Comment by brianjjones** [comment]
@grgustaf error added for DEV

**Comment by grgustaf** [comment]
+1

**Pull request merged**
