### PR TITLE
[general] Wait on semaphore in main loop

### PR DESCRIPTION
**Pull request by jprestwo**
Signed-off-by: James Prestwood <james.prestwood@intel.com>

### CODE REVIEW

**Comment by poussa** [comment]
What is the issue this PR is fixing?

**Comment by grgustaf** [comment]
Discussed elsewhere, we should do some work to demonstrate some facts about how our system works and prove this is superior before merging. In particular, I'd like to see something that logs the timings of a faster timer running in JS, e.g. setInterval with a timeout of 10ms and log when exactly those callbacks occur. I'd like to see e.g. what the average time between callbacks is and their standard deviation. Does this improve with the patch?

We suspected maybe power usage would improve with this patch but based on our limited testing it didn't, so I think we need this kind of timing analysis to see whether we've really made things better.

I suspect that with our old sleep method, we might have slept through an entire tick now and then, causing timer events to double up in the next tick. I'm hoping we'll be able to see that by capturing some data. And then maybe that goes away or is minimized with this semaphore approach.

**Comment by grgustaf** [comment]
@jimmy-huang were you able to confirm a positive impact from this patch?

**Comment by jimmy-huang** [comment]
@jprestwo can you rebase this? I can try it out today

**Comment by grgustaf** [comment]
Well we still can't point to this specifically improving any real-world results, but we believe it is a better approach, so no time like right at the start of a release cycle to merge it.

**Comment by grgustaf** [comment]
+1

**Pull request merged**
