### PR TITLE
[Makefile] Build JerryScript directly, instead of recursively via Zephyr.

### PR DESCRIPTION
**Pull request by pfalcon**
Such recursive approach no longer works with current upstream JerryScript
and leads to confusing errors.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
Fixes https://github.com/01org/zephyr.js/issues/501 . Note - JrS upgrade is not included in this PR, can be done later, or I can add it here.

**Comment by grgustaf** [comment]
+1, need conflicts resolved

**Comment by poussa** [comment]
+1, need conflicts resolved.

Glad to see Makefile.app to go way, that was hackish solution anyway.

**Comment by pfalcon** [comment]
Patch rebased and retested.

Note that LTO breaks more things than just frdm_k64f: https://github.com/01org/zephyr.js/pull/495#issuecomment-265500924

**Comment by jimmy-huang** [comment]
@pfalcon yeah, it's probably ARM in general, not just frdm_k64f, but for now we only have 2 boards, we can probably change the check if arch is not ARM.

ifneq ($(ARCH), arm)?

**Comment by pfalcon** [comment]
> but for now we only have 2 boards

Well, I'm working (and submitting patches) towards supporting more (actually, any board supported by Zephyr).

> ifneq ($(ARCH), arm)?

Unfortunately, ARCH isn't available in Z.js Makefile. If the current usecase is to optimize code size for arduino_101, then perhaps following would be good for now?

~~~
ifeq ($(BOARD), arduino_101)
~~~

**Comment by grgustaf** [comment]
>~~~
>ifeq ($(BOARD), arduino_101)
>~~~

Sounds right to me for now.

**Comment by jimmy-huang** [comment]
yeah, that's good

**Comment by grgustaf** [comment]
conflicts resolved, merging

**Pull request merged**
