### PR TITLE
[BLE] Fixes disconnect callback not getting called

### LINKED ISSUE #1088: [ble] Disconnect can't trigger callback function
### Description

Disconnect can't trigger callback function
 
### Test Code

[BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js); [test-ble.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ble.js)
 
### Steps to Reproduction

1. `make JS=samples/BLE.js ROM=256`
2. `make dfu`
3. Connect A101 with Nexus 5 via nRF app.
4. Disconnect ble connection from nRF app side.

### Actual Result

No disconnection info is outputted while connection broke up in nRF app.
selection_062
 
### Expected Result

BLE disconnection info prints when try to disconnect from nRF app.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 78bc531 | Arduino 101 | May 3, 2017 | Fail

### PR DESCRIPTION
**Pull request by jimmy-huang**
The issue is that the c callback is immediately removed
after the callback is signaled, and the main loop have not
serviced the callback yet.  We don't need to keep a separate
callback for each connection anyway, so instead use
a singal C callback for connect and disconnects.

Fixes #1088

Signed-off-by: Jimmy Huang <jimmy.huang@intel.com>

### CODE REVIEW

**Comment by grgustaf** [comment]
@jimmy-huang, @jprestwo - from the description of the first patch it sure sounds like you're looking for zjs_add_callback_once?

**Comment by jprestwo** [comment]
@jimmy-huang and I discussed and yes a way to add a C callback "one time" is a clean solution. There are a few other places where this would be beneficial. The workaround currently is to remove the callback inside the C callback, which works, but you do have to know the ID.

**Comment by grgustaf** [comment]
Oh I see, we don't already have that function for C, only for JS callbacks? Well we could either merge this first and then address that when we like, or do it now - either way is fine.

**Comment by grgustaf** [comment]
+1

**Pull request merged**
