### PR TITLE
[ashell] Adding echo command

### PR DESCRIPTION
**Pull request by brianjjones**
This adds the echo command, which when turned off will prevent
commands from being printed in the console.

Original patch by Sudarsana Nagineni <sudarsana.nagineni@intel.com>

Signed-off-by: Brian Jones <brian.j.jones@intel.com>

### CODE REVIEW

**Comment by nagineni** [comment]
IDE side changes here - https://github.com/01org/zephyrjs-ide/pull/127/commits/dc2223e

**Comment by nagineni** [comment]
I just noticed that this PR has the old commit of echo command functionality. I will create a new one with the correct fix.

**Comment by brianjjones** [comment]
@nagineni FYI the reason ashell is failing the build is due to lack of memory.  I'm going to have to do a bit of work to get things to fit again.  Sorry for that, I'll keep you posted.

**Comment by brianjjones** [comment]
@nagineni OK got it shrunk down, just let me know where your new changes are and I'll use them instead.

**Comment by nagineni** [comment]
@brianjjones you can cherry-pick from my branch here https://github.com/nagineni/zephyr.js/commits/echo_mode  or I can create a separate PR with all these changes.

**Comment by brianjjones** [comment]
@nagineni The only difference I see in that branch is the "comms_println("echo_on");" and echo_off prints.  I intentionally removed those as @poussa had asked we cut down on the chatter seen in the console.  Is there a reason for the print other than extra information?  If so could it possibly be a DBG print instead?

**Comment by nagineni** [comment]
@brianjjones Those messages are needed to inform the IDE back that the echo mode is off/on so that the IDE can prevent printing duplicate prompts (i.e 'acm>') received from ashell on the console. Note that we are already handling those messages in the IDE and skipping them so they don't appear on the console.

This is the output we see in the console when the echo mode is off:

JS: console.log("Hello World!!");

Output:

```
acm> 
Hello World!!
acm> 
```

**Comment by nagineni** [comment]
I just created a new PR with all the changes here https://github.com/01org/zephyr.js/pull/1120

**Comment by brianjjones** [comment]
Closing this one in favor of #1120

**Pull request closed without merging**
