### PR TITLE
[callbacks] Return this from some methods to support chaining

### PR DESCRIPTION
**Pull request by gabrielschulhof**
This unifies the interface with that of node.js. The methods that support
chaining are:
- add_listener
- remove_listener
- remove_all_listener
- set_max_listeners

### CODE REVIEW

**Comment by brianjjones** [comment]
@gabrielschulhof I'm afraid this PR fails when running samples/tests/Events.js.  I see only this in the console:

ipm_console0: 'Sensor core running ZJS ARC support image'
exit

Can you do a bit of digging to see why it fails?  If I use a clean copy of master it works.

**Comment by grgustaf** [comment]
@jprestwo could you take a look at this?

**Comment by jprestwo** [comment]
I have had problems of returning 'this' from a function. I never got down to what was wrong but the program would just sit there and spin. It could be a JerryScript problem. But I can take a look again and try and get down to why its not working. It could be because we have to acquire 'this' and return the acquired value? I don't believe I tried that when I was seeing this problem before.

**Comment by jimmy-huang** [comment]
@jprestwo I don't think you'll need to acquire the 'this' object before, so this patch looks okay, if you can test it out if it's not breaking anything, we can merge this.

**Comment by brianjjones** [comment]
@jimmy-huang I tested it earlier and it fails on samples/tests/Events.js  Unless Events.js needs to be changed to work with this new patch, I don't think it works as intended and breaks functionality.

**Comment by grgustaf** [comment]
This is still targeting "devel" - it needs a rebase to master, or else we can manually merge it when it's ready if there's any confusion about how to do that.

**Comment by brianjjones** [comment]
I've rebased this and created a new pull request here https://github.com/01org/zephyr.js/pull/431

**Comment by jimmy-huang** [comment]
I am going to close this as #431 is already merged.

**Pull request closed without merging**
