### PR TITLE
Ashell refactoring

### PR DESCRIPTION
**Pull request by zolkis**
**WIP. Do not merge yet.**

Created a directory src/bshell that contains the refactored version of src/ashell.
Compilation is switched from src/Makefile.base, line 115.
The intent is to test and improve the refactored version, then when it's sufficiently good, merge into ashell.

Main changes in this PR:
- make transport (uart, webusb, ble, etc) switchable
- removed IHEX
- simplified the overall structure
- refactored functions
- echo on/off is done with control characters.

When WebUSB will be supported with Zephyr net_buf instead of UART, then comms-uart.c can be compiled away (later change).

TODO:
- segmentation/reassembly support for UART
- many control characters are not supported in `ashell` nor `bshell` (need to use ANSI escape sequences). 
- tab auto-completion, command history with up-down arrows, etc.

Needs a patch to zephyrjs-ide.
```patch
diff --git a/src/client/app/shared/webusb/webusb.port.ts b/src/client/app/shared/webusb/webusb.port.ts
index fb0ddaa..47d87a3 100644
--- a/src/client/app/shared/webusb/webusb.port.ts
+++ b/src/client/app/shared/webusb/webusb.port.ts
@@ -99,7 +99,7 @@ export class WebUsbPort {
 
     public read(): Promise<string> {
         return new Promise<string>((resolve, reject) => {
-            this.device.transferIn(3, 64).then((response: any) => {
+            this.device.transferIn(3, 68).then((response: any) => {
                 let decoded = this.decoder.decode(response.data);
                 resolve(decoded);
             });
@@ -118,29 +118,21 @@ export class WebUsbPort {
         });
     }
 
-    public run(data: string): Promise<string> {
+    public run(data: string, ihex: boolean = false): Promise<string> {
         return new Promise<string>((resolve, reject) => {
             if (data.length === 0) {
                 reject('Empty data');
             }
-
-            this.send('set transfer ihex\n')
-                .then(() => this.send('stop\n'))
-                .then(() => this.send('load\n'))
-                .then(() => {
-                    let ihex =
-                        this.convIHex(
-                            this.stripBlankLines(
-                                this.stripComments(data)));
-
-                    for (let line of ihex.split('\n')) {
-                        this.send(line + '\n');
-                    }
+            this.send('\x1D' + 'stop\n')  // ECHO OFF + stop
+            .then(() => this.send('save temp.dat\r\n'))
+            .then(() => {
+                  this.send(
+                      this.stripBlankLines(
+                          this.stripComments(data)) + '\x1A' + '\n');  // data + EOF
                 })
-                .then(() => this.send('run temp.dat\n'))
-                .then(() => this.send('set transfer raw\n'))
-                .then((warning: string) => resolve(warning))
-                .catch((error: string) => reject(error));
+            .then(() => this.send('run temp.dat' + '\x1E' + '\n'))  // ECHO ON
+            .then((warning: string) => resolve(warning))
+            .catch((error: string) => reject(error));
         });
     }
```

### CODE REVIEW

**Comment by grgustaf** [comment]
Hi, we got the big build refactoring patch in which was holding up much else - so we should be able to take a good look at this soon. Looks like there's a build problem with webusb_serial though. It probably shouldn't be building two copies for one thing?

This is the kind of thing which might well get broken by that new build patch though since it's one of the more subtle things in our build, reusing a source file form inside Zephyr.

**Comment by zolkis** [comment]
Looks like I will need to refactor the refactoring in order to make more meaningful commits for the same tip-to-tip changes, e.g. "remove IHEX", "modularize transports", "add echo through control chars", "rename this-or-that" etc. Still WIP. Don't yet spend time with looking at this.

**Comment by grgustaf** [comment]
@zolkis should I now spend time looking at this? :)

**Comment by zolkis** [comment]
@grgustaf yes, thank you. Tell me if the changes are untrackable, then I will spend time to make another PR with better constructed commits (doing one thing at a time, and now it's more clear what those things need to be). This PR is more like an exploratory blob.

I still need to add segmentation/reassembly, but I am busy with WoT stuff now.

**Comment by brianjjones** [comment]
@zolkis Should we close this in favor of  #1567?

**Comment by zolkis** [comment]
I thought to close this when the other PR is merged and refactoring is done. But of course it can be closed also now.

**Comment by grgustaf** [comment]
Closing in favor of upcoming PR

**Pull request closed without merging**
