### PR TITLE
[gpio/uart] Removed promise dependency from GPIO/UART

### PR DESCRIPTION
**Pull request by jprestwo**
Signed-off-by: James Prestwood <james.prestwood@intel.com>

### CODE REVIEW

**Comment by jprestwo** [comment]
This is in preparation for the big promise patch/update #1058. With JrS promises built in, ashell overflows since GPIO and UART use promises. Since the use of promises in these modules was not required (the operations were sync anyways) we can go with a sync version. This patch needs to and should go in before #1058.

**Comment by zolkis** [comment]
Are these operations synchronous on all boards?

**Comment by jprestwo** [comment]
@zolkis, on all our supported boards they are. Every board I have come into contact with has had a synchronous "open" API for hardware modules. The only API that I can think that *may* be async (on some boards) and use a callback (in C) would be UART.write(), but again in our case even this is synchronous.

**Comment by zolkis** [comment]
Thanks. That simplifies things a lot.

**Comment by grgustaf** [comment]
+1

**Pull request merged**
