### PR TITLE
[tests] Update test-uart.js for bug fix

### PR DESCRIPTION
**Pull request by cuiyanx**
Fix bug for #854 

**TOTAL:** 9 of 9 passed

Signed-off-by: Cui, Yan yanx.cui@intel.com

### CODE REVIEW

**Comment by jimmy-huang** [comment]
@cuiyanx please update the copyright in the test-uart.js file

**Comment by jprestwo** [comment]
+1 LGTM

**Comment by jimmy-huang** [comment]
@cuiyanx can you add signed-off by in your commit msg

**Comment by cuiyanx** [comment]
Update all and one commit.

**Comment by grgustaf** [comment]
+1

**Comment by grgustaf** [comment]
BTW try to describe the bug fix in your comment rather than just say "bug fix".

**Comment by cuiyanx** [comment]
@grgustaf OK, I will improve my description.

**Pull request merged**
